spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mitraa_hackathons?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: root
    password: NewPassword123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    session:
      cookie:
        secure: false

app:
  bootstrap-admin:
    enabled: true
    email: sk.litonn1@gmail.com
    password: "MitraaAdmin@123"