package com.mitraa.hackathon.guardian;
import com.mitraa.hackathon.notification.NotificationService;
import com.mitraa.hackathon.registration.*;
import com.mitraa.hackathon.user.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.*;
@Service
public class GuardianConsentService {
 private final UserRepository users; private final RegistrationRepository registrations; private final GuardianConsentRepository consents; private final PasswordEncoder encoder; private final NotificationService notifications; private final SecureRandom random=new SecureRandom();
 public GuardianConsentService(UserRepository u,RegistrationRepository r,GuardianConsentRepository c,PasswordEncoder e,NotificationService n){users=u;registrations=r;consents=c;encoder=e;notifications=n;}
 @Transactional public void request(String userEmail){Registration r=registration(userEmail);if(!r.isGuardianConsentRequired())throw new IllegalArgumentException("Guardian consent is not required for this participant.");if(!"DOB_VERIFIED".equals(r.getAgeVerificationStatus()))throw new IllegalArgumentException("The participant date of birth has not passed eligibility validation.");if(r.isGuardianConsentReceived())return;if(r.getGuardianEmail()==null||r.getGuardianEmail().isBlank())throw new IllegalArgumentException("Guardian email is missing. Contact support.");Instant now=Instant.now();var latest=consents.findTopByRegistrationAndConsumedAtIsNullOrderByCreatedAtDesc(r);if(latest.isPresent()&&latest.get().getCreatedAt().isAfter(now.minusSeconds(60)))throw new IllegalArgumentException("Please wait 60 seconds before requesting another guardian code.");if(consents.countByRegistrationAndCreatedAtAfter(r,now.minus(Duration.ofHours(1)))>=5)throw new IllegalArgumentException("Guardian code request limit reached. Try again after one hour.");latest.ifPresent(c->{c.setConsumedAt(now);consents.save(c);});String otp=String.format("%06d",random.nextInt(1_000_000));GuardianConsent c=new GuardianConsent();c.setRegistration(r);c.setCodeHash(encoder.encode(otp));c.setExpiresAt(now.plus(Duration.ofMinutes(10)));consents.save(c);notifications.queueGuardianConsent(r,otp);}
 @Transactional(noRollbackFor=IllegalArgumentException.class) public void verify(String userEmail,GuardianVerifyRequest request,String ip,String userAgent){Registration r=registration(userEmail);if(!r.isGuardianConsentRequired())throw new IllegalArgumentException("Guardian consent is not required.");if(request==null||!request.allAccepted())throw new IllegalArgumentException("All guardian confirmations and legal acknowledgements are required.");GuardianConsent c=consents.findTopByRegistrationAndConsumedAtIsNullOrderByCreatedAtDesc(r).orElseThrow(()->new IllegalArgumentException("Invalid or expired guardian code."));if(c.getExpiresAt().isBefore(Instant.now())||c.getAttempts()>=5)throw new IllegalArgumentException("Guardian code expired or locked. Request a new code.");c.setAttempts(c.getAttempts()+1);if(request.otp()==null||!request.otp().matches("\\d{6}")||!encoder.matches(request.otp(),c.getCodeHash())){consents.save(c);throw new IllegalArgumentException("Invalid guardian code.");}Instant now=Instant.now();c.setConsumedAt(now);c.setConsentedAt(now);c.setConsentIp(limit(ip,64));c.setConsentUserAgent(limit(userAgent,500));c.setLegalVersion("2026-08-28");consents.save(c);r.setGuardianConsentReceived(true);r.setStatus(RegistrationStatus.PENDING_SUBMISSION);registrations.save(r);notifications.queueGuardianConfirmed(r);}
 private String limit(String value,int max){if(value==null)return null;return value.length()<=max?value:value.substring(0,max);}
 private Registration registration(String email){User u=users.findByEmailIgnoreCase(email).orElseThrow();return registrations.findByUser(u).orElseThrow();}
}
