ALTER TABLE users ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0, ADD COLUMN locked_until TIMESTAMP(6) NULL;
ALTER TABLE teams ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'LOCKED', ADD COLUMN locked_at TIMESTAMP(6) NULL, ADD COLUMN leader_user_id BIGINT NULL;
UPDATE teams t JOIN registrations r ON r.id=t.registration_id SET t.leader_user_id=r.user_id,t.locked_at=t.created_at;
ALTER TABLE teams MODIFY leader_user_id BIGINT NOT NULL, ADD CONSTRAINT fk_team_leader FOREIGN KEY(leader_user_id) REFERENCES users(id);
ALTER TABLE team_members ADD COLUMN invitation_status VARCHAR(24) NOT NULL DEFAULT 'ACCEPTED', ADD COLUMN invitation_token_hash VARCHAR(64) NULL, ADD COLUMN invited_at TIMESTAMP(6) NULL, ADD COLUMN responded_at TIMESTAMP(6) NULL, ADD COLUMN linked_user_id BIGINT NULL, ADD CONSTRAINT fk_team_member_user FOREIGN KEY(linked_user_id) REFERENCES users(id);
UPDATE team_members duplicate_member JOIN team_members retained_member ON LOWER(duplicate_member.email)=LOWER(retained_member.email) AND duplicate_member.id>retained_member.id SET duplicate_member.invitation_status='REMOVED';
ALTER TABLE team_members ADD COLUMN active_email VARCHAR(190) GENERATED ALWAYS AS (CASE WHEN invitation_status IN ('PENDING','ACCEPTED') THEN LOWER(email) ELSE NULL END) STORED;
CREATE UNIQUE INDEX uk_team_member_active_email ON team_members(active_email);
CREATE UNIQUE INDEX uk_team_member_token ON team_members(invitation_token_hash);
ALTER TABLE notification_outbox ADD COLUMN read_at TIMESTAMP(6) NULL;

CREATE TABLE support_tickets(id BIGINT NOT NULL AUTO_INCREMENT,ticket_number VARCHAR(32) NOT NULL,user_id BIGINT NOT NULL,category VARCHAR(24) NOT NULL,subject VARCHAR(160) NOT NULL,status VARCHAR(24) NOT NULL,priority VARCHAR(16) NOT NULL,assigned_admin_id BIGINT NULL,created_at TIMESTAMP(6) NOT NULL,updated_at TIMESTAMP(6) NOT NULL,closed_at TIMESTAMP(6) NULL,PRIMARY KEY(id),UNIQUE KEY uk_support_ticket_number(ticket_number),KEY idx_support_user(user_id,updated_at),KEY idx_support_status(status,priority),CONSTRAINT fk_support_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_support_admin FOREIGN KEY(assigned_admin_id) REFERENCES users(id));
CREATE TABLE support_messages(id BIGINT NOT NULL AUTO_INCREMENT,ticket_id BIGINT NOT NULL,author_user_id BIGINT NOT NULL,message TEXT NOT NULL,internal_note BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP(6) NOT NULL,PRIMARY KEY(id),KEY idx_support_message(ticket_id,created_at),CONSTRAINT fk_support_message_ticket FOREIGN KEY(ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE,CONSTRAINT fk_support_message_author FOREIGN KEY(author_user_id) REFERENCES users(id));

CREATE TABLE certificates(id BIGINT NOT NULL AUTO_INCREMENT,certificate_number VARCHAR(48) NOT NULL,verification_token VARCHAR(64) NOT NULL,user_id BIGINT NOT NULL,submission_id BIGINT NULL,certificate_type VARCHAR(24) NOT NULL,status VARCHAR(20) NOT NULL,issued_at TIMESTAMP(6) NOT NULL,revoked_at TIMESTAMP(6) NULL,revocation_reason VARCHAR(500) NULL,download_count BIGINT NOT NULL DEFAULT 0,last_downloaded_at TIMESTAMP(6) NULL,PRIMARY KEY(id),UNIQUE KEY uk_certificate_number(certificate_number),UNIQUE KEY uk_certificate_token(verification_token),UNIQUE KEY uk_certificate_user_type(user_id,certificate_type),KEY idx_certificate_status(status,certificate_type),CONSTRAINT fk_certificate_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_certificate_submission FOREIGN KEY(submission_id) REFERENCES submissions(id));
CREATE TABLE result_publications(id BIGINT NOT NULL AUTO_INCREMENT,title VARCHAR(160) NOT NULL,embargo_at TIMESTAMP(6) NOT NULL,published BOOLEAN NOT NULL DEFAULT FALSE,published_at TIMESTAMP(6) NULL,approved_by BIGINT NULL,created_at TIMESTAMP(6) NOT NULL,PRIMARY KEY(id),CONSTRAINT fk_result_approver FOREIGN KEY(approved_by) REFERENCES users(id));
