ALTER TABLE registrations ADD COLUMN terms_accepted_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE registrations ADD COLUMN privacy_accepted_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE registrations ADD COLUMN rules_accepted_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE registrations ADD COLUMN marketing_consent BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE teams (id BIGINT AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(24) NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT uk_team_registration UNIQUE (registration_id), CONSTRAINT uk_team_code UNIQUE (code), CONSTRAINT fk_team_registration FOREIGN KEY (registration_id) REFERENCES registrations(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_members (id BIGINT AUTO_INCREMENT PRIMARY KEY, team_id BIGINT NOT NULL, full_name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, date_of_birth DATE NOT NULL, country VARCHAR(80) NOT NULL, guardian_consent BOOLEAN NOT NULL DEFAULT FALSE, CONSTRAINT fk_member_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_team_members_team ON team_members(team_id);
CREATE TABLE submissions (id BIGINT AUTO_INCREMENT PRIMARY KEY, registration_id BIGINT NOT NULL, project_name VARCHAR(140) NOT NULL, problem_statement VARCHAR(2000) NOT NULL, solution_summary VARCHAR(4000) NOT NULL, technology_stack VARCHAR(1000) NOT NULL, repository_url VARCHAR(500), demo_url VARCHAR(500), responsible_ai VARCHAR(2000) NOT NULL, status VARCHAR(30) NOT NULL, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), submitted_at TIMESTAMP(6), CONSTRAINT uk_submission_registration UNIQUE (registration_id), CONSTRAINT fk_submission_registration FOREIGN KEY (registration_id) REFERENCES registrations(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_submissions_status ON submissions(status);
